a = input("enter first sring:")
b = input("enter first sring:")
c = input("enter first sring:")
d = input("enter first sring:")
e = input("enter first sring:")
a = a.replace(" ", "")
b = b.replace(" ", "")
c = c.replace(" ", "")
d = d.replace(" ", "")
e = e.replace(" ", "")
print("length of A:", len(a),"length of A:", len(a),"length of B:", len(b),"length of C:", len(c),"length of D:", len(d))
